### PR TITLE
Add build

### PR DESCRIPTION
**Pull request by parsley72**

### CODE REVIEW

**Comment by parsley72** [comment]
Build works for me: https://github.com/parsley72/IoTGoat/actions/runs/11412668338

**Comment by scriptingxss** [comment]
Thank you for the PR @parsley72. Would you please summarize the functionality and some of what you intend with adding builds? Are we expected to see build artifacts are stored after one is complete? appreciate it!

**Comment by parsley72** [comment]
Why do you need a reason for getting the build to work? I wanted to get the build to work, it didn't work so I fixed it.

**Comment by scriptingxss** [comment]
Thank you for getting the build to work and surfacing a gap in this project for contributors. I have added the standard [OWASP Contribution guidelines ](https://github.com/OWASP/IoTGoat/blob/master/CONTRIBUTING.md)that all projects abide by. Im specifically asking for `5. Your pull request includes a clear and concise description of the changes you have made.` I appreciate you taking the time to fix the build issue and providing the required information to review so I can get this merged. Thank you!

**Comment by parsley72** [comment]
The commit comments are comprehensive and include links to sources.

**Pull request merged**
