### PR TITLE
Add Docker setup for IoTGoat with QEMU and QCOW2 support

### LINKED ISSUE #4: IoTGoat as a container
Run IoTGoat within a docker container https://github.com/openwrt/docker

### PR DESCRIPTION
**Pull request by lefanous**
**Description:**

This PR adds Docker support for running IoTGoat with QEMU, allowing the use of a QCOW2 image for virtualization.

It includes:

- A Dockerfile.qemu for setting up the QEMU environment.
- docker-compose.yml for simplified service orchestration.
- Instructions in the docker/README.md to guide users on fetching the QCOW2 image and running the environment using Docker.
- This resolves the need for containerized virtualization discussed in Issue #4.

**Changes:**

- Added Docker setup for IoTGoat with QEMU and QCOW2 support.
- Updated project structure to support Docker files.
- Provided documentation for setup and usage.

This closes [#4](https://github.com/OWASP/IoTGoat/issues/4).

### CODE REVIEW

**Comment by lefanous** [comment]
@scriptingxss I am not able to add a reviewer — can you take a look at the PR?

**Comment by scriptingxss** [comment]
Thank you for the PR. Ive been looking forward to this! Please allow me time to review and test for this change, hopefully within the week. I appreciate your patience

**Comment by scriptingxss** [comment]
Walking through the readme and the commit, I dont have the same docker file structure between steps 2 and 3 after converting the image to qcow2 at `The image should be added to the docker directory`. How/when is the IoTGoat/docker directory created? 
```
IoTGoat/
│
├── docker/                       # Docker files and configs
│   ├── Dockerfile.qemu           # QEMU environment setup
│   ├── docker-compose.yml        # Docker Compose config
│   ├── IoTGoat-x86.qcow2         # QCOW image (add manually)
│   └── README.md                 # Docker and QCOW setup instructions
│...
```

**Comment by lefanous** [comment]
> Walking through the readme and the commit, I dont have the same docker file structure between steps 2 and 3 after converting the image to qcow2 at `The image should be added to the docker directory`. How/when is the IoTGoat/docker directory created?
> 
> ```
> IoTGoat/
> │
> ├── docker/                       # Docker files and configs
> │   ├── Dockerfile.qemu           # QEMU environment setup
> │   ├── docker-compose.yml        # Docker Compose config
> │   ├── IoTGoat-x86.qcow2         # QCOW image (add manually)
> │   └── README.md                 # Docker and QCOW setup instructions
> │...
> ```

Thank you for the feedback. Please give me time to revise.

**Comment by lefanous** [comment]
> Walking through the readme and the commit, I dont have the same docker file structure between steps 2 and 3 after converting the image to qcow2 at `The image should be added to the docker directory`. How/when is the IoTGoat/docker directory created?
> 
> ```
> IoTGoat/
> │
> ├── docker/                       # Docker files and configs
> │   ├── Dockerfile.qemu           # QEMU environment setup
> │   ├── docker-compose.yml        # Docker Compose config
> │   ├── IoTGoat-x86.qcow2         # QCOW image (add manually)
> │   └── README.md                 # Docker and QCOW setup instructions
> │...
> ```

I've just looked it through — the docker directory is in the committed files. Are you sure you've pulled the right branch? I've just tried to replicate it and it is included here.

Let me know if anything isn't adding up!

**Pull request merged**
